name: auth_server
description: arowana example.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_jsonwebtoken: ^2.3.2
  arowana: ^0.0.2
  sqlite3: ^1.2.0
  crypto: ^3.0.1
#  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
